# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Minimage"
license = "MIT"
licenselink = "https://github.com/d-kusk/minimage/blob/master/LICENSE.md"
description = "It is simple, thumbnail can be set theme."
homepage = "https://github.com/d-kusk/minimage/"
tags = ["responsive", "simple"]
features = ["Responsive", "Thumbnail", "JSON-LD"]
min_version = "0.26"

[author]
  name = "Daisuke KONISHI"
  homepage = "https://dasiukekonishi.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
